name: Validate JSONs

on: [pull_request, push]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Validate tags JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/tags_schema.json
          jsons: ./files/json/tags.json
          
      - name: Validate address objects JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/addr_obj_schema.json
          jsons: ./files/json/addr_obj.json

      - name: Validate address group JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/addr_group_schema.json
          jsons: ./files/json/addr_group.json
          
      - name: Validate anti spyware JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/anti_spyware_schema.json
          jsons: ./files/json/spyware.json
          
      - name: Validate antivirus JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/antivirus_schema.json
          jsons: ./files/json/antivirus.json

      - name: Validate file blocking JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/file_blocking_schema.json
          jsons: ./files/json/file_blocking.json

      - name: Validate nat JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/NAT_schema.json
          jsons: ./files/json/nat.json

      - name: Validate security policy JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/sec_policy_schema.json
          jsons: ./files/json/sec_policy.json

      - name: Validate services JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/services_schema.json
          jsons: ./files/json/services.json

      - name: Validate vulnerability JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/vulnerability_schema.json
          jsons: ./files/json/vulnerability.json

      - name: Validate wildfire analysis JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/wildfire_schema.json
          jsons: ./files/json/wildfire.json