name: Check for JSON duplicates
on: [push]

jobs:
  opa_eval:
    runs-on: ubuntu-latest
    name: Open Policy Agent
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Evaluate OPA Policy w/anti_spyware
      id: opa_eval_antispyware
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/json/spyware.json
        
    - name: Print Results antispyware
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_antispyware.outputs.opa_results }}


    - name: Evaluate OPA Policy w/antivirus
      id: opa_eval_antivirus
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/json/antivirus.json
        
    - name: Print Results antivirus
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_antivirus.outputs.opa_results }}


    - name: Evaluate OPA Policy w/file_blocking
      id: opa_eval_file_blocking
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/json/file_blocking.json
        
    - name: Print Results file blocking
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_file_blocking.outputs.opa_results }}
      
    - name: Print Results vulnerability
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_vulnerability.outputs.opa_results }}


    - name: Evaluate OPA Policy w/wildfire
      id: opa_eval_wildfire
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/json/wildfire.json
    
    - name: Print Results wildfire
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_wildfire.outputs.opa_results }}